ramenskoye:
    short_name: ram
    dbname: db_ram
    name: раменское
    api: 1
    'x': 55.5708624
    'y': 38.1913837
    time_zone: Europe/Moscow

zhukovsky:
    short_name: zhuk
    dbname: db_zhuk
    name: жуковский
    api: 1
    'x': 55.5700441
    'y': 38.0624557
    time_zone: Europe/Moscow

#yerevan:
#    short_name: yer
#    dbname: db_zhuk
#    name: Ереван
#    api: 1
#    'x': 40.1779424
#    'y': 44.5110678
